### ISSUE TITLE
Cannot install hnswlib on docker

### ISSUE THREAD

**Issue by dabasmoti** [nmslib/hnswlib#320]
Faild to install 0.3.4 version and the latest on docker image?
Why is that happend?

Docker:

FROM 

```
python:3.7-slim
WORKDIR /app
RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean
```

```
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from hnswlib==0.5.1) (1.18.4)
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpb64xmdd7
       cwd: /tmp/pip-req-build-n6bzh1ac
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_ext
  creating tmp
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c /tmp/tmp32qsfnfu.cpp -o tmp/tmp32qsfnfu.o -std=c++14
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c /tmp/tmpv9g9ql47.cpp -o tmp/tmpv9g9ql47.o -std=c++11
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 119, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-xvicn3h7/overlay/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 96, in build_extensions
      opts.append(cpp_flag(self.compiler))
    File "setup.py", line 69, in cpp_flag
      raise RuntimeError('Unsupported compiler -- at least C++11 support '
  RuntimeError: Unsupported compiler -- at least C++11 support is needed!
  ----------------------------------------
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib which use PEP 517 and cannot be installed directly
```
I am running on debian , and i have the gcc compiler
```

Python 3.7.10 (default, May 12 2021, 16:15:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
Thanks.

**Comment by satyak450** [comment]
Hey @dabasmoti, did you ever figure out the solution?

**Comment by dabasmoti** [comment]
As far as i can remember, It was compiler issue.
