### ISSUE TITLE
amazon linux python 3.10 aarch64: Unsupported compiler -- at least C++11 support is needed!

### ISSUE THREAD

**Issue by tekumara** [nmslib/hnswlib#505]
```
bash-4.2# pip install hnswlib
Collecting hnswlib
  Downloading hnswlib-0.7.0.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from hnswlib)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/b1/39/3f88e2bfac1fb510c112dc0c78a1e7cad8f3a2d75e714d1484a044c56682/numpy-1.25.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.6 kB)
Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating tmp
      /usr/bin/aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw -I/tools/deps/libedit/include -fPIC -I/usr/local/include/python3.10 -c /tmp/tmp01l956bu.cpp -o tmp/tmp01l956bu.o -std=c++14
      /usr/bin/aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw -I/tools/deps/libedit/include -fPIC -I/usr/local/include/python3.10 -c /tmp/tmphmbrrdan.cpp -o tmp/tmphmbrrdan.o -std=c++11
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 116, in <module>
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-9i51uibi/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 103, in build_extensions
        File "<string>", line 70, in cpp_flag
      RuntimeError: Unsupported compiler -- at least C++11 support is needed!
      [end of output]
```

**Comment by tekumara** [comment]
When [building extension wheels](https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#compiler-and-linker-options) setuptools will try to use the compiler (ie: `CC`) used to build python itself ...

In my case, my [python binary](https://github.com/indygreg/python-build-standalone) was built on ubuntu where `CC` was set to _/usr/bin/aarch64-linux-gnu-gcc_:

```
$ python3 -m sysconfig | grep -E '\bCC ='
        CC = "/usr/bin/aarch64-linux-gnu-gcc"
```

But amazon/redhat linux has:
```
$ ls /usr/bin/ | grep gcc
aarch64-redhat-linux-gcc
aarch64-redhat-linux-gcc-7
```

So when I use my binary python on amazon linux it can't find gcc. To resolve this, override `CC` with an env var, eg:
```
export CC = gcc
```
or link _/usr/bin/aarch64-linux-gnu-gcc_ -> _gcc_
